default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: video_playlist_development

test:
  <<: *default
  database: video_playlist_test

production:
  <<: *default
  database: video_playlist_production
  username: video_playlist
  password: <%= ENV['VIDEO_PLAYLIST_DATABASE_PASSWORD'] %>
